function jtsToast(message){const node=document.getElementById('toast');if(!node)return;node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2200)}
function jtsEscape(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function jtsDate(){return document.getElementById('attendanceDate').value||new Date().toISOString().slice(0,10)}
function jtsDay(date){if(!attendance[date])attendance[date]={status:'draft',submitted:false,approved:false,records:{}};if(!attendance[date].records)attendance[date].records={};return attendance[date]}
function jtsRecord(date,id){const day=jtsDay(date);if(!day.records[id])day.records[id]={status:'pending',hours:0,overtime:0};return day.records[id]}
function jtsMarked(date){const day=jtsDay(date);return workers.filter(worker=>worker.active&&['present','worked','absent'].includes(day.records?.[worker.id]?.status))}
function renderJtsAttendancePage(){const date=jtsDate(),query=document.getElementById('workerSearch').value.trim().toLowerCase(),day=jtsDay(date),marked=jtsMarked(date),matches=query.length<2?[]:workers.filter(worker=>worker.active&&!marked.some(item=>item.id===worker.id)&&[worker.name,worker.idNumber,worker.employeeNo].some(value=>String(value||'').toLowerCase().includes(query))).slice(0,20),present=marked.filter(worker=>['present','worked'].includes(day.records[worker.id].status)).length,absent=marked.filter(worker=>day.records[worker.id].status==='absent').length;
 document.getElementById('summary').innerHTML=`<div class="summary-card"><strong>${workers.filter(worker=>worker.active).length}</strong><span>Expected</span></div><div class="summary-card"><strong>${present}</strong><span>Present</span></div><div class="summary-card"><strong>${absent}</strong><span>Absent</span></div><div class="summary-card"><strong>${marked.length}</strong><span>Marked</span></div>`;
 document.getElementById('searchResults').innerHTML=query.length<2?'':matches.map(worker=>`<button class="worker-result" onclick="markJtsPresent(${worker.id})"><span><strong>${jtsEscape(worker.name)}</strong><small>${jtsEscape(worker.idNumber||worker.employeeNo||'')}</small></span><b>Mark present</b></button>`).join('')||'<div class="empty">No matching unmarked worker.</div>';
 document.getElementById('markedTable').innerHTML=marked.map(worker=>{const record=day.records[worker.id],status=record.status==='worked'?'present':record.status;return `<tr><td><input class="jts-select" type="checkbox" value="${worker.id}"></td><td><strong>${jtsEscape(worker.name)}</strong></td><td>${jtsEscape(worker.idNumber||worker.employeeNo||'')}</td><td><span class="status status-${status==='present'?'worked':status==='absent'?'absent':'pending'}">${jtsEscape(status)}</span></td><td>${Number(record.hours||0)}</td><td>${Number(record.overtime||0)}</td><td><button class="secondary" onclick="editJtsRecord(${worker.id})">Edit</button> <button class="danger" onclick="cancelJtsRecord(${worker.id})">Cancel</button></td></tr>`}).join('')||'<tr><td colspan="7"><div class="empty">Search for a worker above to begin marking attendance.</div></td></tr>'}
function markJtsPresent(id){const date=jtsDate(),day=jtsDay(date);if(day.submitted||day.approved){jtsToast('This attendance copy is final.');return}const record=jtsRecord(date,id);record.status='present';record.hours=9;record.overtime=0;localStorage.setItem('labourforce_attendance_dirty','1');saveData();document.getElementById('workerSearch').value='';renderJtsAttendancePage();jtsToast('Worker marked present.');}
function editJtsRecord(id){const date=jtsDate(),day=jtsDay(date);if(day.submitted||day.approved){jtsToast('Final attendance cannot be edited.');return}const record=jtsRecord(date,id),hours=prompt('Regular hours:',String(record.hours||9));if(hours===null)return;const overtime=prompt('Overtime hours:',String(record.overtime||0));if(overtime===null)return;record.status='present';record.hours=Math.min(24,Math.max(0,Number(hours)||0));record.overtime=Math.max(0,Number(overtime)||0);record.remarks=prompt('Remarks (optional):',record.remarks||'')||'';localStorage.setItem('labourforce_attendance_dirty','1');saveData();renderJtsAttendancePage();}
function cancelJtsRecord(id){const date=jtsDate(),day=jtsDay(date);if(day.submitted||day.approved){jtsToast('Final attendance cannot be cancelled.');return}const record=day.records?.[id];if(record){record.status='pending';record.hours=0;record.overtime=0;record.remarks='';localStorage.setItem('labourforce_attendance_dirty','1');saveData();renderJtsAttendancePage();jtsToast('Attendance mark cancelled.');}}
function selectedJtsIds(){return [...document.querySelectorAll('.jts-select:checked')].map(input=>Number(input.value))}
document.getElementById('attendanceDate').value=new Date().toISOString().slice(0,10);document.getElementById('workerSearch').addEventListener('input',renderJtsAttendancePage);document.getElementById('attendanceDate').addEventListener('change',renderJtsAttendancePage);document.getElementById('editSelected').onclick=()=>{const ids=selectedJtsIds();if(ids.length!==1)return jtsToast('Select one marked worker to edit.');editJtsRecord(ids[0])};document.getElementById('cancelSelected').onclick=()=>{const ids=selectedJtsIds();if(!ids.length)return jtsToast('Select marked workers first.');ids.forEach(cancelJtsRecord)};document.getElementById('submitFinal').onclick=()=>{const date=jtsDate(),day=jtsDay(date),marked=jtsMarked(date);if(!marked.length)return jtsToast('Mark at least one worker first.');if(confirm(`Submit ${marked.length} marked worker(s) as the final copy?`)){day.submitted=true;day.status='submitted';day.submittedAt=new Date().toISOString();localStorage.setItem('labourforce_attendance_dirty','1');saveData();renderJtsAttendancePage();jtsToast('Final attendance copy submitted.')}};renderJtsAttendancePage();
