/* ============================================================
   /verify � worker attendance verification page
   Standalone. No localStorage as source-of-truth.
   No supervisor app, no payroll, no local attendance cache.
   All data comes directly from Supabase via Edge Functions.
   ============================================================ */

(function(){
'use strict';

// -- Supabase client (independent of the main app's auth state) --
// /verify does NOT use Supabase Auth. Each worker verifies via a
// dedicated Edge Function. The anon key is safe here because every
// privileged operation is gated by Edge Function business logic.

let vfSb = null;
try {
  if (window.supabase && window.LABOUR_FORCE_SUPABASE_URL && window.LABOUR_FORCE_SUPABASE_ANON_KEY) {
    vfSb = window.supabase.createClient(
      window.LABOUR_FORCE_SUPABASE_URL,
      window.LABOUR_FORCE_SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }
    );
  }
} catch (e) { console.error('[verify] supabase init failed', e); }

// Edge Function base � set by the deploy. Override here if hosting
// the functions on a different URL (e.g. localhost during development).
const VF_VERIFY_URL  = 'https://xliclazgekuokvpcwiyq.supabase.co/functions/v1/worker-verify-pin';
const VF_UPDATE_URL  = 'https://xliclazgekuokvpcwiyq.supabase.co/functions/v1/worker-update-pin';
const VF_ATTEND_URL  = 'https://xliclazgekuokvpcwiyq.supabase.co/functions/v1/worker-attendance';

// Secure session token (NOT the PIN itself, NOT the worker_id alone).
// Generated by /verify on first verify; stored in sessionStorage so it
// dies with the tab. Used by Edge Functions to gate attendance reads.
const VF_SESSION_KEY = 'vf_session';

const MONTHS = ['January','February','March','April','May','June',
                'July','August','September','October','November','December'];
const DOW    = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];

let vfState = {
  worker_id:    null,
  employee_no:  null,
  full_name:    null,
  session_token: null,
  // The currently viewed month. Anchored on the user's local clock;
  // /verify is single-worker so timezone-shifting is benign.
  year:  null,
  month: null,   // 0-11
};

// -- DOM helpers ----------------------------------------------
function $(id){ return document.getElementById(id); }
function addShow(el){ if (el) el.classList.add("show"); }
function removeShow(el){ if (el) el.classList.remove("show"); }
function show(el){ if (el) el.style.display = ''; }
function hide(el){ if (el) el.style.display = 'none'; }
function esc(s){
  if (s == null) return '';
  return String(s).replace(/[&<>"']/g, c => (
    {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]
  ));
}
// -- Login flow -----------------------------------------------
function vfDoLogin(){
  const idEl   = $('vfWorkerId');
  const pinEl  = $('vfPin');
  const errEl  = $('vfLoginError');
  const btn    = $('vfLoginBtn');
  if (!idEl || !pinEl) return;

  const employeeNo = (idEl.value || '').trim().toUpperCase();
  const pin        = (pinEl.value || '').trim();
  if (errEl) { errEl.classList.remove('show'); errEl.textContent = ''; }

  if (!employeeNo || !pin) {
    if (errEl) { errEl.textContent = 'Please enter your National ID and password.'; errEl.classList.add('show'); }
    return;
  }
  if (!vfSb) {
    if (errEl) { errEl.textContent = 'Verification service unavailable. Please try again later.'; errEl.classList.add('show'); }
    return;
  }

  btn.disabled = true;
  btn.classList.add('loading');
  btn.setAttribute('aria-busy', 'true');
  vfCallVerify(employeeNo, pin)
    .then(function(result){
      if (!result.ok) {
        // Generic error to avoid leaking which field was wrong
        if (errEl) { errEl.textContent = 'National ID or password is incorrect.'; errEl.classList.add('show'); }
        return;
      }
      // Save session
      vfState.worker_id    = result.worker_id;
      vfState.employee_no  = result.employee_no;
      vfState.full_name    = result.full_name;
      vfState.session_token = result.session_token;
      try { sessionStorage.setItem(VF_SESSION_KEY, JSON.stringify({
        worker_id:     vfState.worker_id,
        employee_no:   vfState.employee_no,
        full_name:     vfState.full_name,
        session_token: vfState.session_token,
      })); } catch (e) { /* sessionStorage may be disabled */ }

      if (result.is_default) {
        // Force PIN creation
        vfOpenForceChangePin();
        return;
      }
      vfShowAttendance();
    })
    .catch(function(err){
      if (err && err.name === 'AbortError') {
        if (errEl) { errEl.textContent = 'Connection timed out. Check your internet.'; errEl.classList.add('show'); }
      } else {
        if (errEl) { errEl.textContent = 'Unable to verify. Check your connection.'; errEl.classList.add('show'); }
      }
    })
    .then(function(){
      btn.disabled = false;
      btn.classList.remove('loading');
      btn.removeAttribute('aria-busy');
    });
}

// Calls the worker-verify-pin Edge Function. The anon key in the
// Authorization header is the only credential sent; the function
// itself uses the service_role key to look up the PIN hash server-side.
function vfCallVerify(employeeNo, pin){
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 8000);
  return fetch(VF_VERIFY_URL, {
    method:  'POST',
    signal: controller.signal,
    headers: {
      'Content-Type': 'application/json',
      'apikey':       window.LABOUR_FORCE_SUPABASE_ANON_KEY || '',
      'Authorization':'Bearer ' + (window.LABOUR_FORCE_SUPABASE_ANON_KEY || ''),
    },
    body: JSON.stringify({ employee_no: employeeNo, pin: pin }),
  })
  .then(function(r){
    clearTimeout(timeoutId);
    if (!r.ok) {
      // Map known HTTP statuses to the same generic worker-facing message
      if (r.status === 401 || r.status === 403) return { ok: false, error: 'invalid' };
      if (r.status >= 500)                     return { ok: false, error: 'service' };
      return { ok: false, error: 'invalid' };
    }
    return r.json();
  });
}
// -- Attendance view -------------------------------------------
function vfShowAttendance(){
  var loginEl = $('vfLogin');
  if (loginEl) loginEl.style.display = 'none';
  removeShow($('vfStateError'));
  var attEl = $('vfAttendance');
  if (attEl) attEl.classList.add('show');

  var now = new Date();
  vfState.year  = now.getFullYear();
  vfState.month = now.getMonth();

  // Populate worker bar (.show class makes it visible)
  var bar = $('vfWorkerBar');
  if (bar) bar.classList.add('show');
  var nameEl = $('vfWorkerName');
  var idEl   = $('vfWorkerIdDisplay');
  var avEl   = $('vfAvatar');
  if (nameEl) nameEl.textContent = vfState.full_name || 'Worker';
  if (idEl)   idEl.textContent   = (vfState.employee_no || '');
  if (avEl) {
    var initials = (vfState.full_name || '?').split(' ').map(function(w){ return w[0]||''; }).slice(0,2).join('').toUpperCase();
    avEl.textContent = initials;
  }

  // Show welcome banner with worker name (it was previously hidden)
  var wbEl = $('vfWelcomeBanner');
  var wnEl = $('vfWelcomeName');
  if (wbEl) wbEl.classList.add('show');
  if (wnEl) wnEl.textContent = vfState.full_name || 'Worker';
  var hdrBtn = $('vfSignOut');
  if (hdrBtn) hdrBtn.style.display = '';

  vfLoadMonth();
}

function vfLoadMonth(){
  addShow($('vfLoading'));
  addShow($('vfMonthNav'));
  addShow($('vfCalendar'));
  addShow($('vfLegend'));
  addShow($('vfSummary'));
  removeShow($('vfStateError'));

  var year  = vfState.year;
  var month = vfState.month; // 0-11
  var monthLabel = MONTHS[month] + ' ' + year;
  var labelEl = $('vfMonthLabel');
  if (labelEl) labelEl.textContent = monthLabel;

  // Prev = disable if the month is in the future (allow navigating to current month only)
  var now = new Date();
  var isCurrentMonth = (year === now.getFullYear() && month === now.getMonth());
  var isFutureMonth  = (year > now.getFullYear()) ||
                        (year === now.getFullYear() && month > now.getMonth());
  var prevBtn = $('vfPrevMonth');
  var nextBtn = $('vfNextMonth');
  if (prevBtn) prevBtn.disabled = isFutureMonth || isCurrentMonth;
  if (nextBtn) nextBtn.disabled = false;

  var start = new Date(year, month, 1);
  var end   = new Date(year, month + 1, 0); // last day of month

  // Fetch attendance via Edge Function (server-side RLS: worker_id = session worker)
  vfFetchAttendance(start, end)
    .then(function(records){
      // records: { attendance_date: 'YYYY-MM-DD', status: string }
      var byDate = {};
      records.forEach(function(r){
        byDate[r.attendance_date] = r.status;
      });
      vfRenderCalendar(year, month, byDate);
      vfRenderSummary(records);
      removeShow($('vfLoading'));
    })
    .catch(function(err){
      console.error('[verify] attendance fetch failed', err);
      removeShow($('vfLoading'));
      addShow($('vfStateError'));
      var tEl = $('vfStateErrorTitle');
      var mEl = $('vfStateErrorMsg');
      if (tEl) tEl.textContent = 'Unable to load attendance';
      if (mEl) mEl.textContent = 'Unable to load your attendance. Please try again.';
    });
}

// Fetches attendance records for the given date range via Edge Function.
// The Edge Function enforces worker_id from the session_token so a
// malicious browser cannot swap the worker_id parameter.
function vfFetchAttendance(startDate, endDate){
  var startStr = startDate.toISOString().slice(0, 10);
  var endStr   = endDate.toISOString().slice(0, 10);
  var body = {
    session_token:  vfState.session_token || '',
    worker_id:     vfState.worker_id,
    range_start:   startStr,
    range_end:     endStr,
  };
  return fetch(VF_ATTEND_URL, {
    method:  'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey':       window.LABOUR_FORCE_SUPABASE_ANON_KEY || '',
      'Authorization':'Bearer ' + (window.LABOUR_FORCE_SUPABASE_ANON_KEY || ''),
    },
    body: JSON.stringify(body),
  })
  .then(function(r){
    if (!r.ok) {
      if (r.status === 401 || r.status === 403) {
        // Session expired
        vfClearSession();
        addShow($('vfLogin'));
        removeShow($('vfAttendance'));
        var errEl = $('vfLoginError');
        if (errEl) { errEl.textContent = 'Your session has expired. Please verify again.'; errEl.classList.add('show'); }
        return [];
      }
      throw new Error('attendance_fetch_failed');
    }
    return r.json();
  })
  .then(function(data){
    if (data.error) throw new Error(data.error);
    return data.records || [];
  });
}
// -- Calendar rendering ----------------------------------------
// Status mapping follows the existing attendance.status check constraint
// in schema_patch_jts_payroll.sql:
//   pending | present | absent | approved
// 'worked' and 'present' from the legacy app also map to worked.
// Future / unfinalized dates are explicitly NOT marked absent � the cell
// shows pending (�) when no row exists for a future date.
function vfStatusCategory(status){
  switch (status) {
    case 'present':
    case 'worked':
    case 'approved':
      return 'worked';
    case 'absent':
      return 'absent';
    case 'pending':
    default:
      return 'pending';
  }
}

function vfRenderCalendar(year, month, byDate){
  var grid = $('vfCalGrid');
  if (!grid) return;
  grid.innerHTML = '';

  // Days in month
  var firstDay    = new Date(year, month, 1);
  var lastDay     = new Date(year, month + 1, 0);
  var daysInMonth = lastDay.getDate();

  // Compute leading blanks. JavaScript getDay() returns 0 = Sunday.
  // We use Mon-first ordering. Convert Sun(0) -> 6, Mon(1) -> 0, etc.
  var firstDow = firstDay.getDay(); // 0..6
  var lead = (firstDow + 6) % 7;    // shift so Mon = 0

  for (var i = 0; i < lead; i++) {
    var blank = document.createElement('div');
    blank.className = 'vf-cal-empty';
    grid.appendChild(blank);
  }

  // Today marker
  var today = new Date();
  today.setHours(0,0,0,0);
  var monthEnd = new Date(year, month + 1, 0);
  monthEnd.setHours(0,0,0,0);

  for (var d = 1; d <= daysInMonth; d++) {
    var cellDate  = new Date(year, month, d);
    cellDate.setHours(0,0,0,0);
    var dateStr = cellDate.toISOString().slice(0, 10);
    var status  = byDate[dateStr] || null;
    var isFuture = cellDate.getTime() >  today.getTime();
    var isToday  = cellDate.getTime() === today.getTime();
    var isPast   = cellDate.getTime() <  today.getTime();

    var cat = status ? vfStatusCategory(status) : (isFuture ? 'pending' : (isPast ? 'absent' : 'pending'));
    // CRITICAL: only mark 'absent' if there is an explicit status row.
    // A missing row for a past date stays as 'pending' (we don't have
    // enough business-rule visibility to know if they were absent, on
    // leave, on a public holiday, or a weekend shift worker).
    // The supervisor portal feeds back into the system before this
    // page ever shows a finalised past date as '�'.
    if (cat === 'absent' && !status) cat = 'pending';

    var cell = document.createElement('div');
    cell.className = 'vf-cal-day ' + ({
      'worked': 'vf-worked',
      'absent': 'vf-absent',
      'pending':'vf-pending',
    }[cat]);

    var mark = document.createElement('div');
    mark.className = 'vf-cal-mark';
    mark.textContent = ({
      'worked': '\u2713',
      'absent': '\u2014',
      'pending':'\u00B7',
    }[cat]);

    var num = document.createElement('div');
    num.className = 'vf-cal-num';
    num.textContent = d;

    cell.appendChild(num);
    cell.appendChild(mark);
    if (isToday) cell.classList.add('vf-today');
    if (isFuture) cell.classList.add('vf-future');
    grid.appendChild(cell);
  }
}

function vfRenderSummary(records){
  // Only count records that explicitly have a status. Per the task spec:
  // "Only count finalized statuses. Do not count pending/future days as absent."
  var worked = 0, absent = 0;
  records.forEach(function(r){
    var cat = vfStatusCategory(r.status);
    if (cat === 'worked') worked++;
    else if (cat === 'absent') absent++;
  });
  var wEl = $('vfSummaryWorked');
  var aEl = $('vfSummaryAbsent');
  if (wEl) wEl.textContent = worked;
  if (aEl) aEl.textContent = absent;
}
// -- Month navigation ------------------------------------------
function vfChangeMonth(delta){
  // Restrict navigation to current or past months (forward is fine � a
  // worker can preview next month if they want). We never let the
  // picker go further into the future than next month from "today".
  var now = new Date();
  var next = new Date(vfState.year, vfState.month + delta, 1);
  if (delta > 0) {
    var farFuture = new Date(now.getFullYear(), now.getMonth() + 1, 1);
    if (next.getTime() > farFuture.getTime()) return;
  }
  vfState.year  = next.getFullYear();
  vfState.month = next.getMonth();
  vfLoadMonth();
}

// -- PIN change flow ------------------------------------------
function vfOpenChangePin(){
  var m       = $('vfPinModal');
  var t       = $('vfPinModalTitle');
  var d       = $('vfPinModalDesc');
  var oldEl   = $('vfOldPinField');
  var oldInp  = $('vfOldPin');
  var newInp  = $('vfNewPin');
  var conInp  = $('vfConfirmPin');
  var msg     = $('vfPinModalMsg');
  if (!m) return;
  if (t) t.textContent = 'Change Your Password';
  if (d) d.textContent = 'Enter your current password, then choose a new one (min 4 characters). The default password "jts" is not allowed.';
  if (oldEl) oldEl.style.display = '';
  if (oldInp) oldInp.value = '';
  if (newInp) newInp.value = '';
  if (conInp) conInp.value = '';
  if (msg) { msg.style.display = 'none'; msg.className = 'vf-modal-msg'; msg.textContent = ''; }
  m.classList.add('open');
  setTimeout(function(){ if (oldInp) oldInp.focus(); }, 60);
}

// First-login forced PIN change � same modal, slightly different copy,
// no "current PIN" field (the Edge Function accepts the just-issued session).
function vfOpenForceChangePin(){
  var m       = $('vfPinModal');
  var t       = $('vfPinModalTitle');
  var d       = $('vfPinModalDesc');
  var oldEl   = $('vfOldPinField');
  var oldInp  = $('vfOldPin');
  var newInp  = $('vfNewPin');
  var conInp  = $('vfConfirmPin');
  var msg     = $('vfPinModalMsg');
  if (t) t.textContent = 'Create Your Password';
  if (d) d.textContent = 'You are using the default password "jts". Please create a new password (min 4 characters) to continue.';
  if (oldEl) oldEl.style.display = 'none';
  if (oldInp) oldInp.value = 'jts'; // server verifies this against the default hash
  if (newInp) newInp.value = '';
  if (conInp) conInp.value = '';
  if (msg) {
    msg.className = 'vf-modal-msg info';
    msg.textContent = 'You must change your PIN before continuing.';
    msg.style.display = '';
  }
  m.classList.add('open');
  setTimeout(function(){ if (newInp) newInp.focus(); }, 60);
}

function vfCloseChangePin(){
  var m = $('vfPinModal');
  if (m) m.classList.remove('open');
}

function vfSavePin(){
  var oldInp  = $('vfOldPin');
  var newInp  = $('vfNewPin');
  var conInp  = $('vfConfirmPin');
  var msg     = $('vfPinModalMsg');
  var btn     = $('vfSavePinBtn');
  if (!oldInp || !newInp || !conInp) return;

  var oldPin = oldInp.value || '';
  var newPin = newInp.value || '';
  var conPin = conInp.value || '';
  if (msg) { msg.className = 'vf-modal-msg'; msg.textContent = ''; msg.style.display = 'none'; }

  if (newPin.length < 4) {
    if (msg) { msg.textContent = 'New PIN must be at least 4 characters.'; msg.className = 'vf-modal-msg'; msg.style.display = ''; }
    newInp.focus();
    return;
  }
  if (newPin === 'jts') {
    if (msg) { msg.textContent = 'You cannot keep the default PIN. Please choose a different one.'; msg.className = 'vf-modal-msg'; msg.style.display = ''; }
    newInp.focus();
    return;
  }
  if (newPin !== conPin) {
    if (msg) { msg.textContent = 'New PIN and confirmation do not match.'; msg.className = 'vf-modal-msg'; msg.style.display = ''; }
    conInp.focus();
    return;
  }

  btn.disabled = true;
  btn.textContent = 'Saving...';
  fetch(VF_UPDATE_URL, {
    method:  'POST',
    headers: {
      'Content-Type': 'application/json',
      'apikey':        window.LABOUR_FORCE_SUPABASE_ANON_KEY || '',
      'Authorization': 'Bearer ' + (window.LABOUR_FORCE_SUPABASE_ANON_KEY || ''),
    },
    body: JSON.stringify({
      worker_id:    vfState.worker_id,
      old_pin:      oldPin,
      new_pin:      newPin,
      confirm_pin:  conPin,
      session_token: vfState.session_token || '',
    }),
  })
  .then(function(r){ return r.json().then(function(j){ return { status: r.status, body: j }; }); })
  .then(function(res){
    if (res.status === 200 && res.body && res.body.ok) {
      if (msg) { msg.textContent = 'PIN updated successfully.'; msg.className = 'vf-modal-msg success'; msg.style.display = ''; }
      setTimeout(function(){ vfCloseChangePin(); }, 900);
    } else {
      var err = (res.body && res.body.error) || 'update_failed';
      var map = {
        'invalid_old_pin':    'Current PIN is incorrect.',
        'pin_too_short':      'New PIN must be at least 4 characters.',
        'same_as_default':    'You cannot keep the default PIN.',
        'pin_mismatch':       'New PIN and confirmation do not match.',
        'unauthorized':       'Your session has expired. Please verify again.',
        'not_found':          'Worker record not found.',
        'update_failed':      'Unable to update PIN. Please try again.',
      };
      if (msg) { msg.textContent = map[err] || 'Unable to update PIN. Please try again.'; msg.className = 'vf-modal-msg'; msg.style.display = ''; }
    }
  })
  .catch(function(){
    if (msg) { msg.textContent = 'Network error. Please try again.'; msg.className = 'vf-modal-msg'; msg.style.display = ''; }
  })
  .then(function(){
    btn.disabled = false;
    btn.textContent = 'Save PIN';
  });
}

// -- Sign-out / session management -----------------------------
function vfSignOut(){
  vfClearSession();
  var loginEl = $('vfLogin');
  if (loginEl) loginEl.style.display = '';
  var attEl = $('vfAttendance');
  if (attEl) attEl.classList.remove('show');
  removeShow($('vfStateError'));
  var hdrBtn = $('vfSignOut');
  if (hdrBtn) hdrBtn.style.display = 'none';
  var idEl = $('vfWorkerId');
  var pEl  = $('vfPin');
  var errEl = $('vfLoginError');
  if (idEl) idEl.value = '';
  if (pEl)  pEl.value  = '';
  if (errEl){ errEl.classList.remove('show'); errEl.textContent = ''; errEl.style.display = 'none'; }
  vfState = { worker_id: null, employee_no: null, full_name: null, session_token: null, year: null, month: null };
}

function vfClearSession(){
  try { sessionStorage.removeItem(VF_SESSION_KEY); } catch (e) {}
}

function vfRetry(){
  removeShow($('vfStateError'));
  if (vfState.worker_id) {
    vfLoadMonth();
  } else {
    addShow($('vfLogin'));
  }
}

// -- Bootstrap: restore session on load ------------------------
function vfInit(){
  // Wire Enter key on PIN field
  var pinEl = $('vfPin');
  if (pinEl) pinEl.addEventListener('keydown', function(e){ if (e.key === 'Enter') vfDoLogin(); });
  var idEl = $('vfWorkerId');
  if (idEl) idEl.addEventListener('keydown', function(e){ if (e.key === 'Enter' && pinEl) pinEl.focus(); });

  // Try to restore an in-tab session
  try {
    var raw = sessionStorage.getItem(VF_SESSION_KEY);
    if (raw) {
      var s = JSON.parse(raw);
      if (s && s.worker_id && s.session_token) {
        vfState.worker_id     = s.worker_id;
        vfState.employee_no   = s.employee_no;
        vfState.full_name     = s.full_name;
        vfState.session_token = s.session_token;
        vfShowAttendance();
        return;
      }
    }
  } catch (e) { /* sessionStorage disabled � proceed to login */ }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', vfInit);
} else {
  vfInit();
}

// Expose a tiny API for the inline onclick handlers. (Using globals
// keeps the markup small and avoids dragging in a bundler.)
window.vfDoLogin        = vfDoLogin;
window.vfSignOut        = vfSignOut;
window.vfChangeMonth    = vfChangeMonth;
window.vfOpenChangePin  = vfOpenChangePin;
window.vfCloseChangePin = vfCloseChangePin;
window.vfSavePin        = vfSavePin;
window.vfRetry          = vfRetry;

})();

